const category = [
    {
        cat_id: "1",
        cat_name: "makeup"
    },
    {
        cat_id: "2",
        cat_name: "skin"
    },
    {
        cat_id: "3",
        cat_name: "hair"
    }
]

const subcategory = [
    {
        cat_id: "1",
        sub_cat_id: "101",
        sub_cat_name: "face"
        // 1001 -1010
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        sub_cat_name: "eyes"
        // 1011-1020
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        sub_cat_name: "lips"
        // 1021-1030
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        sub_cat_name: "nails"
        // 1031-1040
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        sub_cat_name: "tools & brushes"
        // 1041-1050
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        sub_cat_name: "Moisturizer"
        // 1051-1060
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        sub_cat_name: "Cleansers"
        // 1061-1070
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        sub_cat_name: "Body Care"
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        sub_cat_name: "Masks"
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        sub_cat_name: "Eye Care"
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        sub_cat_name: "hair Care "
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        sub_cat_name: "Tools & Accessories "
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        sub_cat_name: " Hair Styling"
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        sub_cat_name: "Shop By Hair Type "
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        sub_cat_name: " Shop By Concern"
    },
]

var productData = [
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1001",
        product_name: "Foundation",
        product_brand:"Maybelline",
        product_description: "Maybelline New York Fit Me Matte+Poreless Liquid Foundation 16H Oil Control SPF22, 128 Warm Nude",
        product_rating: "4.4",
        product_rating_count: "470",
        product_img: "https://images-static.nykaa.com/media/catalog/product/5/3/536bb116902395718338_1.jpg",
        product_price: "750",
        product_discount_price: "525",
        product_discount_percenteage: "30",
        product_color: "golden",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1002",
        product_name: "Setting Spray",
        product_brand:"Lakme",
        product_description: "Insight Cosmetics Make Up Fixer Spray",
        product_rating: "3.4",
        product_rating_count: "4868",
        product_img: "https://images-static.nykaa.com/media/catalog/product/3/9/3900695NYSWISSB00122_1.jpg",
        product_price: "180",
        product_discount_price: "162",
        product_discount_percenteage: "10",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1003",
        product_name: "Sindoor",
        product_brand:"Lakme",
        product_description: "Lakme Jewel Sindoor - Maroon",
        product_rating: "4.7",
        product_rating_count: "5089",
        product_img: "https://images-static.nykaa.com/media/catalog/product/2/8/281af39LAK_8901030174919_0.jpg?tr=w-344,h-344,cm-pad_resize",
        product_price: "190",
        product_discount_price: "172",
        product_discount_percenteage: "10",
        product_color: "Red",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1004",
        product_name: "BB & CC Cream",
        product_brand:"Nivea",
        product_description: "WOW Skin Science Vitamin C Face Serum",
        product_rating: "2.3",
        product_rating_count: "3923",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/5/e569b75WOW_SER_VITC_3.jpg",
        product_price: "699",
        product_discount_price: "489",
        product_discount_percenteage: "30",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1005",
        product_name: "Makeup Remover",
        product_brand:"Lakme",
        product_description: "Clinique Take The Day Off Cleansing Balm (Makeup Remover)",
        product_rating: "3.4",
        product_rating_count: "1492",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/6/d66ef7320714215552_1.jpg",
        product_price: "1200",
        product_discount_price: "1080",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1006",
        product_name: "Spray",
        product_brand:"Olay",
        product_description: "TNW The Natural Wash 100% Steam Distilled Rose Water Face Toner Spray, Make Up Remover & Hydration",
        product_rating: "4.8",
        product_rating_count: "3466",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/c/cc900618908014468019_1.jpg",
        product_price: "450",
        product_discount_price: "351",
        product_discount_percenteage: "22",
        product_color: "Red",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1007",
        product_name: "foundation",
        product_brand:"Lakme",
        product_description: "Lakme Absolute Skin Natural Mousse Mattreal Foundation - Medium Caramel",
        product_rating: "4.5",
        product_rating_count: "1345",
        product_img: "https://images-static.nykaa.com/media/catalog/product/2/7/27129_h-8901030732799m.jpg",
        product_price: "850",
        product_discount_price: "680",
        product_discount_percenteage: "20",
        product_color: "brown",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1008",
        product_name: "Setting Spray",
        product_brand:"Olay",
        product_description: "Swiss Beauty Long Lasting Makeup Fixer Natural Aloe Vera With Vitamin-E",
        product_rating: "2.5",
        product_rating_count: "2543",
        product_img: "https://images-static.nykaa.com/media/catalog/product/3/9/3900695NYSWISSB00122_1.jpg",
        product_price: "249",
        product_discount_price: "199",
        product_discount_percenteage: "20",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1009",
        product_name: "Concealer",
        product_brand:"Maybelline",
        product_description: "Maybelline New York Instant Age Rewind Eraser Multi-Use Concealer - Medium",
        product_rating: "3.7",
        product_rating_count: "3412",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/4/04a1b136902395487432_1.jpg",
        product_price: "620",
        product_discount_price: "528",
        product_discount_percenteage: "15",
        product_color: "golden",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "101",
        product_id: "1010",
        product_name: "Liquid Foundation",
        product_brand:"Nivea",
        product_description: "Daily Life Forever52 Ultra Definition Liquid Foundation",
        product_rating: "2.3",
        product_rating_count: "1243",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/1/9/197954d3592496005036_1.jpg",
        product_price: "949",
        product_discount_price: "835",
        product_discount_percenteage: "12",
        product_color: "brown",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1011",
        product_name: "Contact Lenses",
        product_brand:"Lakme",
        product_description: "O-Lens Coral Scandi Mixed 1day Coloured Contact Lenses - Coral Scandi ( 0.00 )",
        product_rating: "4.6",
        product_rating_count: "200",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/5/b5f333d8882388416756_1.jpg",
        product_price: "1000",
        product_discount_price: "800",
        product_discount_percenteage: "20",
        product_color: "brown",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1012",
        product_name: "Kajal",
        product_brand:"Lakme",
        product_description: "Lakme Eyeconic Kajal - Twin Pack",
        product_rating: "4.2",
        product_rating_count: "1242",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/1/0158c8fLAKME00000332_0.jpg",
        product_price: "629",
        product_discount_price: "528",
        product_discount_percenteage: "15",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1013",
        product_name: "Concealer",
        product_brand:"Olay",
        product_description: "Nykaa SKINgenius Conceal & Correct Palette - Deep 03",
        product_rating: "4.3",
        product_rating_count: "2421",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/8/88e921b8904245704186_1.jpg",
        product_price: "1499",
        product_discount_price: "1199",
        product_discount_percenteage: "20",
        product_color: "golden",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1014",
        product_name: "Makeup Remover",
        product_brand:"Nivea",
        product_description: "Nykaa Makeup Remover Wipes",
        product_rating: "2.4",
        product_rating_count: "122",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8904245712655_1.jpg",
        product_price: "299",
        product_discount_price: "239",
        product_discount_percenteage: "20",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1015",
        product_name: "False Eyelashes",
        product_brand:"Olay",
        product_description: "Swiss Beauty 3d Studio Effect Eyelashes - Drama",
        product_rating: "4.9",
        product_rating_count: "3323",
        product_img: "https://images-static.nykaa.com/media/catalog/product/7/c/7ce78a68904325012897_1.jpg",
        product_price: "129",
        product_discount_price: "115",
        product_discount_percenteage: "10",
        product_color: "brown",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1016",
        product_name: "Mascara",
        product_brand:"Nivea",
        product_description: "Smashbox Mascara + Mini Lash Primer Duo",
        product_rating: "3.2",
        product_rating_count: "1243",
        product_img: "https://images-static.nykaa.com/media/catalog/product/2/0/20fa55aSMASH00000101_0.jpg",
        product_price: "2000",
        product_discount_price: "1400",
        product_discount_percenteage: "30",
        product_color: "Red",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1017",
        product_name: "Eye Brow Enhancers",
        product_brand:"Maybelline",
        product_description: "Blue Heaven Brow Perfect Eyebrow Enhancer Pencil + Comb - Honey Brown",
        product_rating: "4.1",
        product_rating_count: "1230",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/8/c82f2388904214802318_1.jpg",
        product_price: "300",
        product_discount_price: "180",
        product_discount_percenteage: "40",
        product_color: "brown",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1018",
        product_name: "Eye shadow ",
        product_brand:"Olay",
        product_description: "Makeup Revolution Forever Flawless Constellation Eyeshadow Palette",
        product_rating: "1.8",
        product_rating_count: "456",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/0/d0cd6215057566077392_new_0.jpg",
        product_price: "1500",
        product_discount_price: "1310",
        product_discount_percenteage: "10",
        product_color: "Red",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1019",
        product_name: "Mascara",
        product_brand:"Nivea",
        product_description: "Blue Heaven 10x Volumising Mascara - Black",
        product_rating: "1.5",
        product_rating_count: "230",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/1/81f3c8fBLUEH00000390_1.jpg",
        product_price: "90",
        product_discount_price: "77",
        product_discount_percenteage: "15",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "102",
        product_id: "1020",
        product_name: "Eyeliner",
        product_brand:"Lakme",
        product_description: "Faces Canada Magneteyes Eyeliner - Dramatic Black Finish",
        product_rating: "3.9",
        product_rating_count: "1498",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/6/b6a62388903380001075_1.jpg",
        product_price: "249",
        product_discount_price: "187",
        product_discount_percenteage: "25",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1021",
        product_name: "Blush",
        product_brand:"Olay",
        product_description: "Love Earth Multipot-Be The Change Lip Tint with Jojoba Oil and Vitamin E for Lips Eyelids & Cheeks",
        product_rating: "3.1",
        product_rating_count: "897",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/e/0e340c5LE71.jpg",
        product_price: "599",
        product_discount_price: "299",
        product_discount_percenteage: "50",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1022",
        product_name: "Lip Stain",
        product_brand:"Blue Heaven",
        product_description: "Blue Heaven Silk & Stain Lip Stain - Raspberry Love",
        product_rating: "1.3",
        product_rating_count: "45",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/5/45704888904214807344_1.jpg",
        product_price: "400",
        product_discount_price: "160",
        product_discount_percenteage: "60",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1023",
        product_name: "Lip Gloss",
        product_brand:"Blue Heaven",
        product_description: "Renee Cosmetics Me Shine Lip Gloss - Gloss Boss Combo",
        product_rating: "1.9",
        product_rating_count: "391",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/3/43b441bRENEE00000025_1.jpg",
        product_price: "800",
        product_discount_price: "480",
        product_discount_percenteage: "40",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1024",
        product_name: "Lip Liner",
        product_brand:"Olay",
        product_description: "Nykaa Lips Don't Lie! Waterproof Line & Fill Lip Liner - Just Bitten ",
        product_rating: "3.1",
        product_rating_count: "920",
        product_img: "https://images-static.nykaa.com/media/catalog/product/3/9/39988d48904245709112_1.jpg",
        product_price: "399",
        product_discount_price: "299",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1025",
        product_name: "Liquid Lipstick",
        product_brand:"Nivea",
        product_description: "Nykaa Matte to Last! Transfer Proof Liquid Lipstick -Kaveri ",
        product_rating: "3.7",
        product_rating_count: "5895",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8904245706227_1_1.jpg",
        product_price: "649",
        product_discount_price: "325",
        product_discount_percenteage: "50",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1026",
        product_name: "Lip Gloss",
        product_brand:"Blue Heaven",
        product_description: "Nykaa 8hour Lasting Full Cover Matte Gloss - Busy Bee",
        product_rating: "1.6",
        product_rating_count: "786",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/f/4f89bfcNYKAC00000057_1.jpg",
        product_price: "549",
        product_discount_price: "494",
        product_discount_percenteage: "10",
        product_color: "brown",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1027",
        product_name: "Lip Crayon",
        product_brand:"Maybelline",
        product_description: "MARS Won't Budge Won't Smudge Lip Crayon - I Am Strong",
        product_rating: "2.4",
        product_rating_count: "678",
        product_img: "https://images-static.nykaa.com/media/catalog/product/5/5/5537844MARSX00000175_1.jpg",
        product_price: "500",
        product_discount_price: "440",
        product_discount_percenteage: "12",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1028",
        product_name: "Lipstick",
        product_brand:"Nivea",
        product_description: "Kay Beauty Matte Drama Long Stay Lipstick - Premier",
        product_rating: "4.1",
        product_rating_count: "2345",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8904330901438_1.jpg",
        product_price: "1200",
        product_discount_price: "620",
        product_discount_percenteage: "40",
        product_color: "",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1029",
        product_name: "Lipstic",
        product_brand:"Maybelline",
        product_description: "Maybelline New York Color Sensatoinal Creamy Matte",
        product_rating: "2.9",
        product_rating_count: "333",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/e/e/eea767441554429930_1.jpg",
        product_price: "200",
        product_discount_price: "140",
        product_discount_percenteage: "30",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "103",
        product_id: "1030",
        product_name: "Lip Stain",
        product_brand:"Lakme",
        product_description: "IBA Must Have everday Lip & Cheek tint",
        product_rating: "2.3",
        product_rating_count: "345",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/4/8/480382bIBAHA00000042-1nw.jpg",
        product_price: "600",
        product_discount_price: "360",
        product_discount_percenteage: "40",
        product_color: "",
        trending_product: false
    },

    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1031",
        product_name: "Nail Polish",
        product_brand:"Nivea",
        product_description: "Faces Canada Splash Nail Enamel - Princess",
        product_rating: "4.2",
        product_rating_count: "2468",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/d/bdf63298903380021028_1.jpg",
        product_price: "300",
        product_discount_price: "255",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1032",
        product_name: "Nail Polish",
        product_brand:"Maybelline",
        product_description: "Faces Canada Ultime Pro Splash Nail Enamel - Twinkle",
        product_rating: "2.0",
        product_rating_count: "254",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/3/c388a268903380024739_1.jpg",
        product_price: "100",
        product_discount_price: "70",
        product_discount_percenteage: "30",
        product_color: "",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1033",
        product_name: "Nail Polish",
        product_brand:"Olay",
        product_description: "Nykaa Cosmetics Insta Dry Nail Enamel - Reeling Red+Vermillion Views+Raspberry Regram+Pink Profile Combo",
        product_rating: "1.7",
        product_rating_count: "16",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/7/d74b3ebnykac00000519_1.jpg",
        product_price: "900",
        product_discount_price: "765",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1034",
        product_name: "Nail Polish",
        product_brand:"Lakme",
        product_description: "Nykaa Cosmetics Breathable Nail Enamel - Easy Nude + Bare Skin + Slow Love Nude Combo",
        product_rating: "3.2",
        product_rating_count: "465",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/7/d74ec92NYKAB00000659_1.jpg",
        product_price: "800",
        product_discount_price: "400",
        product_discount_percenteage: "50",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1035",
        product_name: "Nail Polish",
        product_brand:"Maybelline",
        product_description: "Nykaa Dual Tone Nail Enamel Remover",
        product_rating: "2.1",
        product_rating_count: "3789",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/5/95365568904245700812_1.jpg",
        product_price: "300",
        product_discount_price: "195",
        product_discount_percenteage: "35",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1036",
        product_name: "Nail Polish",
        product_brand:"Lakme",
        product_description: "Nykaa Nail Care - Going Strong Calcium Milk",
        product_rating: "1.6",
        product_rating_count: "8533",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/8/083a0c58904245704797_0.jpg",
        product_price: "500",
        product_discount_price: "275",
        product_discount_percenteage: "45",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1037",
        product_name: "Nail Polish",
        product_brand:"Lakme",
        product_description: "Lakme Absolute Nail Hardener",
        product_rating: "2.7",
        product_rating_count: "32",
        product_img: "https://images-static.nykaa.com/media/catalog/product/2/f/2f05696LAKME00000218_1.jpg",
        product_price: "300",
        product_discount_price: "225",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1038",
        product_name: "Nail Polish Remover",
        product_brand:"Blue Heaven",
        product_description: "Insight Cosmetics Nail Polish Remover Wipes - Apple",
        product_rating: "1.4",
        product_rating_count: "323",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/7/d70a7bc8904277800672_1.jpg",
        product_price: "50",
        product_discount_price: "45",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1039",
        product_name: "Nail Polish Remover",
        product_brand:"Blue Heaven",
        product_description: "Blue Heaven Dip & Twist Nail Paint Remover",
        product_rating: "1.2",
        product_rating_count: "235",
        product_img: "https://images-static.nykaa.com/media/catalog/product/3/e/3e7d1fc8906028069178_1.jpg",
        product_price: "80",
        product_discount_price: "60",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "104",
        product_id: "1040",
        product_name: "Nail Polish",
        product_brand:"Olay",
        product_description: "LoveChild Masaba - The Classics! Breathable Nail Enamel - 01 Albela",
        product_rating: "2.0",
        product_rating_count: "478",
        product_img: "https://images-static.nykaa.com/media/catalog/product/a/d/ad95ff18906153110240_1.jpg",
        product_price: "225",
        product_discount_price: "191",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },

    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1041",
        product_name: "Brush Set",
        product_brand:"Maybelline",
        product_description: "PAC Absolute Basics Brush Set",
        product_rating: "3.4",
        product_rating_count: "444",
        product_img: "https://images-static.nykaa.com/media/catalog/product/7/3/73c6621nypac00000185_new_1.jpg",
        product_price: "6000",
        product_discount_price: "4200",
        product_discount_percenteage: "30",
        product_color: "Black",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1042",
        product_name: "Makeup Brushes",
        product_brand:"Nivea",
        product_description: "Bronson Professional Mini Makeup Brushes - Set of 12",
        product_rating: "2.7",
        product_rating_count: "2578",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/d/dd9334eNYBRONSON0019_WR%20(1).jpg",
        product_price: "400",
        product_discount_price: "312",
        product_discount_percenteage: "22",
        product_color: "golden",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1043",
        product_name: "Brush Set",
        product_brand:"Olay",
        product_description: "London Pride Cosmetics Prime Hd Professional Brush Set",
        product_rating: "1.3",
        product_rating_count: "10",
        product_img: "https://images-static.nykaa.com/media/catalog/product/5/a/5aa12bf5060501349973_A.JPG",
        product_price: "10000",
        product_discount_price: "8000",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1044",
        product_name: "Brush Set ",
        product_brand:"Blue Heaven",
        product_description: "Bronson Professional Bamboo Makeup Brush Set - 11 Pcs",
        product_rating: "4.2",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/1/9/19387a6brons00000015_1.jpg",
        product_price: "700",
        product_discount_price: "539",
        product_discount_percenteage: "23",
        product_color: "golden",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1045",
        product_name: "Face Brush",
        product_brand:"Maybelline",
        product_description: "Miscellanea Makeup Brush Cleaning Mat",
        product_rating: "5",
        product_rating_count: "1",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/6/0686299MISCE00000034_1.jpg",
        product_price: "900",
        product_discount_price: "774",
        product_discount_percenteage: "14",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1046",
        product_name: "Blush",
        product_brand:"Lakme",
        product_description: "Swiss Beauty Makeup Buddy Beauty Blender - Peach",
        product_rating: "3",
        product_rating_count: "235",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/6/9667b888904325066807_1.jpg",
        product_price: "150",
        product_discount_price: "120",
        product_discount_percenteage: "20",
        product_color: "brown",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1047",
        product_name: "Eye Brow Enhancers",
        product_brand:"Maybelline",
        product_description: "Majestique Silicone Eyelash Curler For Dramatic Long Lasting Seamless Curls (Color May Vary)",
        product_rating: "3.7",
        product_rating_count: "235",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/c/4cf76f28900978809280_%20(1).jpg",
        product_price: "300",
        product_discount_price: "120",
        product_discount_percenteage: "60",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1048",
        product_name: "Tweezers",
        product_brand:"Olay",
        product_description: "Colorbar Wow Brows Flat Tip Tweezer",
        product_rating: "2.3",
        product_rating_count: "211",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/6/0645621cb_8904052467618_new_3.jpg",
        product_price: "400",
        product_discount_price: "180",
        product_discount_percenteage: "55",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1049",
        product_name: "Brush Sets",
        product_brand:"",
        product_description: "Bronson Professional 24 Pcs Makeup Brush Set With Luxury Leather Storage Pouch",
        product_rating: "2.7",
        product_rating_count: "2344",
        product_img: "https://images-static.nykaa.com/media/catalog/product/5/4/54791381528915645253as__1_.jpg",
        product_price: "700",
        product_discount_price: "650",
        product_discount_percenteage: "7",
        product_color: "golden",
        trending_product: true
    },
    {
        cat_id: "1",
        sub_cat_id: "105",
        product_id: "1050",
        product_name: "Sharpener",
        product_brand:"Lakme",
        product_description: "Lakme Dual Sharpener",
        product_rating: "4",
        product_rating_count: "2543",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8901030333125.jpg",
        product_price: "100",
        product_discount_price: "65",
        product_discount_percenteage: "35",
        product_color: "Red",
        trending_product: false
    },


    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1051",
        product_name: "Face Moisturizer & Day Cream",
        product_brand:"Olay",
        product_description: "Aqualogica Glow+ Jello Gel Moisturiser",
        product_rating: "2.9",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/1/1/11cafc5AQUAA00000020_1.jpg",
        product_price: "500",
        product_discount_price: "425",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1052",
        product_name: "Moisturiser",
        product_brand:"Nivea",
        product_description: "Plum Green Tea Renewed Clarity Night Gel",
        product_rating: "1",
        product_rating_count: "121",
        product_img: "https://images-static.nykaa.com/media/catalog/product/1/b/1bbf21e737534800522_1.jpg",
        product_price: "600",
        product_discount_price: "462",
        product_discount_percenteage: "23",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1053",
        product_name: "Face Oil",
        product_brand:"Blue Heaven",
        product_description: "Nykaa Naturals Skin Potion Anti Acne Skincare Face Oil",
        product_rating: "2.2",
        product_rating_count: "3532",
        product_img: "https://images-static.nykaa.com/media/catalog/product/3/1/31a34708904245709693_1.jpg",
        product_price: "900",
        product_discount_price: "585",
        product_discount_percenteage: "35",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1054",
        product_name: "Serums & Essence",
        product_brand:"Lakme",
        product_description: "Minimalist 16% Vitamin C Serum With Vitamin E & Ferulic Acid For Advanced Users",
        product_rating: "4",
        product_rating_count: "342",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/6/e6efa87MINIM00000044_1.jpg",
        product_price: "700",
        product_discount_price: "602",
        product_discount_percenteage: "14",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1055",
        product_name: "Body Lotions & Moisturizers",
        product_brand:"Nivea",
        product_description: "Nivea Soft Combo Pack Of 3",
        product_rating: "3",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/7/d72bed88904256017350-1.jpg",
        product_price: "300",
        product_discount_price: "285",
        product_discount_percenteage: "5",
        product_color: "",
        trending_product: true
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1056",
        product_name: "Body Lotions & Moisturizers",
        product_brand:"Nivea",
        product_description: "Nivea Soft Light Moisturizer Cream Playful Peach For Hands And Body",
        product_rating: "4.5",
        product_rating_count: "345",
        product_img: "https://images-static.nykaa.com/media/catalog/product/6/0/6005d89NIVEA00000061new1.jpg",
        product_price: "700",
        product_discount_price: "490",
        product_discount_percenteage: "30",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1057",
        product_name: "Serums & Essence",
        product_brand:"Olay",
        product_description: "The Pink Foundry 12% Niacinamide Super Clarifying Face Serum",
        product_rating: "4.9",
        product_rating_count: "463",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/4/b487aabTHEAO00000051_1.jpg",
        product_price: "1000",
        product_discount_price: "750",
        product_discount_percenteage: "35",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1058",
        product_name: "Face Oils",
        product_brand:"Maybelline",
        product_description: "Ayuga 100% Kumkumadi Face Oil",
        product_rating: "3.5",
        product_rating_count: "32",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/f/efeb7968906087777304_01.jpg",
        product_price: "1200",
        product_discount_price: "900",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1059",
        product_name: "Night Cream",
        product_brand:"Olay",
        product_description: "Olay Retinol Night Cream - Retinol & Niacinamide - All Skin Types",
        product_rating: "2.7",
        product_rating_count: "564",
        product_img: "https://images-static.nykaa.com/media/catalog/product/a/9/a9eff5c4902430917964.jpg",
        product_price: "2000",
        product_discount_price: "1600",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "106",
        product_id: "1060",
        product_name: "Day Moisturizer",
        product_brand:"Maybelline",
        product_description: "Nykaa SKINRX Vitamin C Illuminate + Day Moisturizer with SPF 15 for Normal to Dry Skin",
        product_rating: "1.2",
        product_rating_count: "457",
        product_img: "https://images-static.nykaa.com/media/catalog/product/5/5/55fea91NYKAB00000508_1.jpg",
        product_price: "600",
        product_discount_price: "492",
        product_discount_percenteage: "18",
        product_color: "",
        trending_product: false
    },


    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1061",
        product_name: "FaceWash",
        product_brand:"Nivea",
        product_description: "Simple Kind To Skin Refreshing Facial Wash",
        product_rating: "4.5",
        product_rating_count: "3423",
        product_img: "https://images-static.nykaa.com/media/catalog/product/6/2/62ec9125011451103863_2.jpg",
        product_price: "400",
        product_discount_price: "100",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1062",
        product_name: "fawashce",
        product_brand:"Olay",
        product_description: "L'Oreal Paris Hydrated, Plump & Radiant Skin Kit",
        product_rating: "3.1",
        product_rating_count: "231",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/4/c4f2851LOREA00000115_1.jpg",
        product_price: "1500",
        product_discount_price: "1125",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1063",
        product_name: "Cleanser",
        product_brand:"Olay",
        product_description: "L'Oreal Paris Revitalift Hyaluronic Acid Hydrating Gel Cleanser",
        product_rating: "2.8",
        product_rating_count: "2322",
        product_img: "https://images-static.nykaa.com/media/catalog/product/6/6/665b3ef2693241_1.jpg",
        product_price: "315",
        product_discount_price: "269",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1064",
        product_name: "Cleanser",
        product_brand:"Maybelline",
        product_description: "Nykaa Naturals Face Scrub",
        product_rating: "2.2",
        product_rating_count: "231",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/n/y/nykab00000175_1.jpg",
        product_price: "350",
        product_discount_price: "280",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1065",
        product_name: "Makeup Remover",
        product_brand:"Blue Heaven",
        product_description: "Mamaearth Micellar Water Foaming Makeup Remover with Rose Water & Glycolic Acid for Makeup Cleansing",
        product_rating: "4.6",
        product_rating_count: "342",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/f/9f7437c8906087773313aw__1_.jpg",
        product_price: "500",
        product_discount_price: "440",
        product_discount_percenteage: "12",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1066",
        product_name: "Makeup Remover",
        product_brand:"Lakme",
        product_description: "Hiphop Micellar Water Makeup Remover Wipes - Pack of 2",
        product_rating: "3.8",
        product_rating_count: "123",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/9/990df89hipho00000004_1.jpg",
        product_price: "198",
        product_discount_price: "178",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1067",
        product_name: "Makeup Remover",
        product_brand:"Olay",
        product_description: "Tulips Refreshing Wet Wipes (Magnolia)",
        product_rating: "2.1",
        product_rating_count: "124",
        product_img: "https://images-static.nykaa.com/media/catalog/product/3/2/3256cdf8904117400857_new1.jpg",
        product_price: "100",
        product_discount_price: "92",
        product_discount_percenteage: "8",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1068",
        product_name: "Makeup Remover",
        product_brand:"Maybelline",
        product_description: "Faces Canada Fresh Clean Glow Makeup Remover Wipes - 10Pcs (Pack of 3)",
        product_rating: "3.7",
        product_rating_count: "234",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/1/410e6218903380008418_new_0.jpg",
        product_price: "250",
        product_discount_price: "188",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1069",
        product_name: "Body Scrubs & Exfoliantsdet",
        product_brand:"Lakme",
        product_description: "MCaffeine Exfoliating Coffee Body Scrub for Tan Removal & Soft-Smooth Skin - 100% Natural & Vegan",
        product_rating: "4.9",
        product_rating_count: "46933",
        product_img: "https://images-static.nykaa.com/media/catalog/product/2/a/2abb563NYKMCF0000002_1.jpg",
        product_price: "800",
        product_discount_price: "640",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "107",
        product_id: "1070",
        product_name: " Scrubs & Exfoliators",
        product_brand:"Nivea",
        product_description: "Palmolive Brightening Souffle Face Scrub",
        product_rating: "4.3",
        product_rating_count: "123",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/1/d1e220bPALMO00000032_1.jpg",
        product_price: "599",
        product_discount_price: "449",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: true
    },



    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1071",
        product_name: "Body Lotions & Moisturizers",
        product_brand:"Nivea",
        product_description: "Nivea Body Lotion Natural Glow, Cell Repair, SPF 15 & 50x Vitamin C",
        product_rating: "1.1",
        product_rating_count: "125",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/2/925e4d14005808427048_1.jpg",
        product_price: "400",
        product_discount_price: "280",
        product_discount_percenteage: "30",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1072",
        product_name: "Body Scrubs & Exfoliants",
        product_brand:"Olay",
        product_description: "Nykaa Wanderlust Cherry Blossom Range & Bath Sponge - Pink Combo",
        product_rating: "4",
        product_rating_count: "1245",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/d/bd4172bNYNYKBC001478_1.jpg",
        product_price: "3000",
        product_discount_price: "2250",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: true
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1073",
        product_name: "Shower Gels & Body Wash",
        product_brand:"Lakme",
        product_description: "The Body Shop Strawberry Shower Gel & Yogurt Combo",
        product_rating: "1.2",
        product_rating_count: "694",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/c/cc4e6d0THEAC00000196.jpg",
        product_price: "1390",
        product_discount_price: "1182",
        product_discount_percenteage: "15",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1074",
        product_name: "Body Butter",
        product_brand:"Maybelline",
        product_description: "The Moms Co. Natural Body Butter",
        product_rating: "3",
        product_rating_count: "332",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/2/5/2528c4f736140999354_1.jpg",
        product_price: "429",
        product_discount_price: "343",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1075",
        product_name: "Bath Salts",
        product_brand:"Olay",
        product_description: "The Body Care Blueberry Bathsalt",
        product_rating: "2.4",
        product_rating_count: "1112",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/l/blueberry_bathsalt.jpg",
        product_price: "325",
        product_discount_price: "293",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1076",
        product_name: "Loofah",
        product_brand:"",
        product_description: "Nykaa Wanderlust Loofah - Lavender",
        product_rating: "2.3",
        product_rating_count: "124",
        product_img: "https://images-static.nykaa.com/media/catalog/product/f/f/fffdcb08904245712969_1.jpg",
        product_price: "249",
        product_discount_price: "212",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1077",
        product_name: "Soaps",
        product_brand:"Nivea",
        product_description: "Fiama Gel Bar Celebration Pack (Buy 4 Get 1 Free)",
        product_rating: "4.6",
        product_rating_count: "2312",
        product_img: "https://images-static.nykaa.com/media/catalog/product/3/9/39efe548901725921545_1new.jpg",
        product_price: "200",
        product_discount_price: "190",
        product_discount_percenteage: "5",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1078",
        product_name: "Shower Gels & Body Wash",
        product_brand:"Nivea",
        product_description: "Nivea Body Wash- Waterlily & Oil Shower Gel Waterlily Flower",
        product_rating: "3.2",
        product_rating_count: "1543",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/a/eab8c3aN_4005808020133_1.jpg",
        product_price: "225",
        product_discount_price: "191",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1079",
        product_name: "Body Scrubs & Exfoliants",
        product_brand:"Olay",
        product_description: "MCaffeine Body Toning & Polishing Kit - Coffee Body Massage Oil, Exfoliating Body Scrub & Body Lotion",
        product_rating: "2.9",
        product_rating_count: "4321",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/2/c2b2509nymcfcom00057_1.jpg",
        product_price: "1400",
        product_discount_price: "1232",
        product_discount_percenteage: "12",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "108",
        product_id: "1080",
        product_name: "Soap",
        product_brand:"Nykaa",
        product_description: "Nykaa  Natural Bathing Soap",
        product_rating: "1.8",
        product_rating_count: "",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/8/9/8904245712761_1_1.jpg",
        product_price: "100",
        product_discount_price: "94",
        product_discount_percenteage: "6",
        product_color: "",
        trending_product: false
    },


    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1081",
        product_name: "Masks & Peels",
        product_brand:"Nykaa",
        product_description: "Nykaa Clay It Cool Ageless Beauty Clay Mask",
        product_rating: "3",
        product_rating_count: "2323",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/2/428f7cb8904245710484_1.jpg",
        product_price: "700",
        product_discount_price: "595",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1082",
        product_name: "Tan Removal Creme",
        product_brand:"",
        product_description: "Raaga Professional De Tan Removal Creme With Kojic & Milk(500 gm)",
        product_rating: "3.9",
        product_rating_count: "1211",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8902979025102_1.jpg",
        product_price: "1155",
        product_discount_price: "1016",
        product_discount_percenteage: "12",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1083",
        product_name: "Masks & Peels",
        product_brand:"Nykaa",
        product_description: "Nykaa Skin Secrets Exotic Indulgence Black Mud + Aloe Vera Sheet Mask For Purified & Hydrated Skin",
        product_rating: "3.2",
        product_rating_count: "12211",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/8/08bd72a8904245704889_1.jpg",
        product_price: "150",
        product_discount_price: "90",
        product_discount_percenteage: "40",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1084",
        product_name: "Masks & Peels",
        product_brand:"Nykaa",
        product_description: "Nykaa Skin Secrets Tea Tree & Salicylic Acid Spot Patch",
        product_rating: "3.7",
        product_rating_count: "985",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8904245712686_01.jpg",
        product_price: "200",
        product_discount_price: "100",
        product_discount_percenteage: "50",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1085",
        product_name: "Masks & Peels",
        product_brand:"Nykaa",
        product_description: "Nykaa Skin Secrets Exotic Indulgence Gold Sheet Mask For Revitalized & Youthful Skin",
        product_rating: "",
        product_rating_count: "",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8904245712280_1.jpg",
        product_price: "120",
        product_discount_price: "94",
        product_discount_percenteage: "22",
        product_color: "golden",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1086",
        product_name: "Hand Creams & Masks",
        product_brand:"Blue Heaven",
        product_description: "Bella Vita Organic De-Tan Face Pack",
        product_rating: "2.2",
        product_rating_count: "921",
        product_img: "https://images-static.nykaa.com/media/catalog/product/6/f/6f2e7aaBELAB00000023-A.jpg",
        product_price: "400",
        product_discount_price: "328",
        product_discount_percenteage: "18",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1087",
        product_name: "Masks & Peels",
        product_brand:"Nykaa",
        product_description: "Nykaa Skin Secrets Retinol & Hyaluronic Acid Sleeping Mask",
        product_rating: "3.8",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/5/c5bf6e08904245713485_1.jpg",
        product_price: "175",
        product_discount_price: "140",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1088",
        product_name: "Masks & Peels",
        product_brand:"Naykaa",
        product_description: "Pilgrim Squalane Glow Sleeping Mask with Alpha Arbutin & Hyaluronic Acid",
        product_rating: "4.8",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/e/8e977608906120583930_1.jpg",
        product_price: "550",
        product_discount_price: "523",
        product_discount_percenteage: "5",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1089",
        product_name: "Masks & Peels",
        product_brand:"Olay",
        product_description: "Bella Vita Organic Vitamin C Glow Face Pack",
        product_rating: "4.2",
        product_rating_count: "25",
        product_img: "https://images-static.nykaa.com/media/catalog/product/1/c/1c86a978906150340275-A.jpg",
        product_price: "399",
        product_discount_price: "299",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "109",
        product_id: "1090",
        product_name: "Masks & Peels",
        product_brand:"Maybelline",
        product_description: "Just Herbs Instaglow Almond Complexion Face Pack for Glowing Skin",
        product_rating: "5",
        product_rating_count: "284",
        product_img: "https://images-static.nykaa.com/media/catalog/product/i/n/instaglow_almond_complexion_pack.jpg",
        product_price: "625",
        product_discount_price: "469",
        product_discount_percenteage: "25",
        product_color: "brown",
        trending_product: false
    },



    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1091",
        product_name: "Eye  Mask",
        product_brand:"Lakme",
        product_description: "Quench Botanics Bravocado Brightening Under Eye Hydrogel Mask",
        product_rating: "2.8",
        product_rating_count: "25",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/5/c5dbf5e8904320724979(1).jpg",
        product_price: "200",
        product_discount_price: "150",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1092",
        product_name: "Eye Mask",
        product_brand:"",
        product_description: "TONYMOLY Panda's Dream Eye Patch",
        product_rating: "",
        product_rating_count: "",
        product_img: "https://images-static.nykaa.com/media/catalog/product/5/6/569600f8806358511708.jpg",
        product_price: "200",
        product_discount_price: "120",
        product_discount_percenteage: "40",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1093",
        product_name: "Eye Masks",
        product_brand:"Olay",
        product_description: "O3+ Power Brightening Anti Dark Circle Eye Sheet Mask",
        product_rating: "4.1",
        product_rating_count: "212",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/6/c61b144O3XXX00000037_1.jpg",
        product_price: "110",
        product_discount_price: "99",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1094",
        product_name: "Eye Makeup Remover",
        product_brand:"",
        product_description: "Garnier Micellar Cleansing Water Pink, For Sensitive Skin",
        product_rating: "3",
        product_rating_count: "6222",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/8/b8b52d36928820029589_1.jpg",
        product_price: "349",
        product_discount_price: "297",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1095",
        product_name: "Eye Care",
        product_brand:"Nivea",
        product_description: "Clinique Hydrate & Glow Set With Moisture Surge 100h",
        product_rating: "",
        product_rating_count: "",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/e/9e3d490CLINI00000214_1.jpg",
        product_price: "3500",
        product_discount_price: "2975",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1096",
        product_name: "Moisturizers",
        product_brand:"Blue Heaven",
        product_description: "MCaffeine Coffee Under Eye Cream for Dark Circle & Puffiness Reduction with Vitamin E & Hyaluronic Acid",
        product_rating: "4.5",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/f/efd9418NYMCFN0000029_1.jpg",
        product_price: "800",
        product_discount_price: "600",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1097",
        product_name: "Moisturizers",
        product_brand:"Maybelline",
        product_description: "Minimalist 10% Multi Peptide Face Serum For Anti Aging & Collagen Boost With Bio-Placenta",
        product_rating: "3",
        product_rating_count: "854",
        product_img: "https://images-static.nykaa.com/media/catalog/product/7/b/7b12eadMINIM00000011n.jpg",
        product_price: "999",
        product_discount_price: "599",
        product_discount_percenteage: "40",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1098",
        product_name: "Moisturizers",
        product_brand:"Maybelline",
        product_description: "MCaffeine Coffee Under Eye Cream for Dark Circle & Puffiness Reduction with Hyaluronic Acid & Vit E",
        product_rating: "4.2",
        product_rating_count: "312",
        product_img: "https://images-static.nykaa.com/media/catalog/product/f/8/f8192d4MCAFF00000222_1.jpg",
        product_price: "500",
        product_discount_price: "325",
        product_discount_percenteage: "35",
        product_color: "Black",
        trending_product: true
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1099",
        product_name: "Eye Band",
        product_brand:"Olay",
        product_description: "MCaffeine Caffeinating Sleeping Eye Mask - Breathable, Lightweight & Travel Friendly Light Blocking Eye Band",
        product_rating: "1.2",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/7/b/7bf2a76MCAFF00000077_1.jpg",
        product_price: "399",
        product_discount_price: "359",
        product_discount_percenteage: "10",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "2",
        sub_cat_id: "110",
        product_id: "1100",
        product_name: "Eye Care Cream",
        product_brand:"Nivea",
        product_description: "PIXI DetoxifEYE Depuffing Under-Eye Patches",
        product_rating: "4.3",
        product_rating_count: "100",
        product_img: "https://images-static.nykaa.com/media/catalog/product/2/b/2b22c08885190822126.png",
        product_price: "3000",
        product_discount_price: "2580",
        product_discount_percenteage: "14",
        product_color: "",
        trending_product: false
    },


    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1101",
        product_name: "Conditioner",
        product_brand:"Olay",
        product_description: "Nykaa Naturals Apple Cider Vinegar & Ginger Anti-Dandruff Paraben and Sulphate Free Conditioner",
        product_rating: "3.2",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/6/8/6815de08904245714017_1.jpg",
        product_price: "600",
        product_discount_price: "390",
        product_discount_percenteage: "35",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1102",
        product_name: "Hair Oil",
        product_brand:"Maybelline",
        product_description: "Mamaearth Onion Hair Oil with Onion & Redensyl for Hair Fall Control",
        product_rating: "2.1",
        product_rating_count: "4211",
        product_img: "https://images-static.nykaa.com/media/catalog/product/7/f/7ff02d18906087771883_GMC_1.jpg",
        product_price: "399",
        product_discount_price: "371",
        product_discount_percenteage: "7",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1103",
        product_name: "Shampoo",
        product_brand:"Maybelline",
        product_description: "Schwarzkopf Professional Bonacure pH 4.5 Color Freeze Sulfate Free Micellar Shampoo",
        product_rating: "1.5",
        product_rating_count: "1233",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/0/4045787428759_1.png",
        product_price: "1000",
        product_discount_price: "950",
        product_discount_percenteage: "5",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1104",
        product_name: " Oil Shampoo",
        product_brand:"Olay",
        product_description: "Tresemme Keratin Smooth With Argan Oil Shampoo",
        product_rating: "4.2",
        product_rating_count: "3231",
        product_img: "https://images-static.nykaa.com/media/catalog/product/6/e/6eb758826117_S1_8901030862861.jpg",
        product_price: "500",
        product_discount_price: "375",
        product_discount_percenteage: "25",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1105",
        product_name: "Dry Shampoo",
        product_brand:"",
        product_description: "Anomaly Refreshing Dry Shampoo with Rice Starch & Tea Tree Oil",
        product_rating: "4",
        product_rating_count: "99",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/3/c3633daANOAA00000006_1.jpg",
        product_price: "900",
        product_discount_price: "700",
        product_discount_percenteage: "22",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1106",
        product_name: "Hairfall & Thinning",
        product_brand:"Olay",
        product_description: "Be Bodywise 5000 Mcg Biotin Gummies For Healthy Hair With Added Zinc & Multivitamins - 120 Day Pack",
        product_rating: "2.4",
        product_rating_count: "231",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/3/e36e036BEBOD00000039_1.jpg",
        product_price: "1998",
        product_discount_price: "1499",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1107",
        product_name: "Conditioner",
        product_brand:"Maybelline",
        product_description: "TNW The Natural Wash Amla Bhringraj Hair Mask for Strong & Smooth Hair - Mask for Hair Fall",
        product_rating: "5",
        product_rating_count: "129",
        product_img: "https://images-static.nykaa.com/media/catalog/product/1/4/14a20618908014468408_1.jpg",
        product_price: "610",
        product_discount_price: "451",
        product_discount_percenteage: "26",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1108",
        product_name: "Hair Serum",
        product_brand:"Lakme",
        product_description: "OGX Renewing Morocco Argan Oil Penetrating Oil(100ml)",
        product_rating: "1.9",
        product_rating_count: "399",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/9/996a5911915591614_A.jpg",
        product_price: "1000",
        product_discount_price: "770",
        product_discount_percenteage: "23",
        product_color: "golden",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1109",
        product_name: "Hair Growth Oil ",
        product_brand:"Blue Heaven",
        product_description: "Blue Heaven Moroccan Argan Hair Growth Oil",
        product_rating: "3.4",
        product_rating_count: "234",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/d/c/dce8a51STBOT478_01.jpg",
        product_price: "899",
        product_discount_price: "584",
        product_discount_percenteage: "35",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "111",
        product_id: "1110",
        product_name: "Shampoo",
        product_brand:"Nykaa",
        product_description: "Nykaa  Shampoo With Marula Oil From Africa",
        product_rating: "3",
        product_rating_count: "89",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/1/4/1499dca8906014764650_0.jpg",
        product_price: "600",
        product_discount_price: "360",
        product_discount_percenteage: "40",
        product_color: "",
        trending_product: false
    },


    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1111",
        product_name: "Hair Brushses",
        product_brand:"Lakme",
        product_description: "Alan Truman-The Blow Brush- Black",
        product_rating: "3.7",
        product_rating_count: "255",
        product_img: "https://images-static.nykaa.com/media/catalog/product/2/5/25831f1712383468857_1.jpg",
        product_price: "3499",
        product_discount_price: "2624",
        product_discount_percenteage: "25",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1112",
        product_name: "Straight",
        product_brand:"Olay",
        product_description: "Olay Truman Blow Brush Silver Ceramic",
        product_rating: "3.3",
        product_rating_count: "50",
        product_img: "https://images-static.nykaa.com/media/catalog/product/a/f/afd61f1ALANT00000054_2.jpg",
        product_price: "3479",
        product_discount_price: "2609",
        product_discount_percenteage: "25",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1113",
        product_name: "Comb",
        product_brand:"Nykaa",
        product_description: "Nykaa Hair Comb Good Looks Combo-Set Of 03",
        product_rating: "1.2",
        product_rating_count: "20",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8906044682566.jpg",
        product_price: "147",
        product_discount_price: "135",
        product_discount_percenteage: "8",
        product_color: "brown",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1114",
        product_name: "Hair Combs",
        product_brand:"Blue Heaven",
        product_description: "Bronson Professional Combs - 10Pcs",
        product_rating: "3.8",
        product_rating_count: "195",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/1/c128113nybronson0055__1_.jpg",
        product_price: "300",
        product_discount_price: "225",
        product_discount_percenteage: "25",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1115",
        product_name: "Hair Accessories",
        product_brand:"Nykaa",
        product_description: "Jewels Galaxy Ad & Pearl Heart Hair Clips Jewellery",
        product_rating: "5",
        product_rating_count: "500",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/e/ee26932ct-hcp-6602_n1.jpg",
        product_price: "2149",
        product_discount_price: "537",
        product_discount_percenteage: "75",
        product_color: "",
        trending_product: true
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1116",
        product_name: "Hair Extensions",
        product_brand:"Nykaa",
        product_description: "Streak Street Clip-In 24 Semi-Wavy Dark Brown Hair Extensions With Golden Highights",
        product_rating: "4.5",
        product_rating_count: "65",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/e/de42f928904368200763_1.jpg",
        product_price: "2599",
        product_discount_price: "1689",
        product_discount_percenteage: "35",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1117",
        product_name: "Hair Wrap",
        product_brand:"Nykaa",
        product_description: "Nykaa Naturals Microfiber Hair Wrap for Frizz Free & Shiny Hair - Lavender",
        product_rating: "4",
        product_rating_count: "1009",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/c/dc6e2c68904245714659_1.jpg",
        product_price: "499",
        product_discount_price: "449",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1118",
        product_name: "Hair Dryer",
        product_brand:"Maybelline",
        product_description: "Maybelline Professional HD Pro 2500+ Hair Dryer (Black)",
        product_rating: "2.6",
        product_rating_count: "120",
        product_img: "https://images-static.nykaa.com/media/catalog/product/3/6/361664a8904231000490_1.jpg",
        product_price: "5500",
        product_discount_price: "4675",
        product_discount_percenteage: "15",
        product_color: "Black",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1119",
        product_name: "Straighten",
        product_brand:"Lakme",
        product_description: "Lakme BHH81600 Crimp Straighten Or Curl With The Single Tool",
        product_rating: "3.9",
        product_rating_count: "45",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/4/44fae00PHIAA00000043_PRW%20(1).jpg",
        product_price: "5000",
        product_discount_price: "4950",
        product_discount_percenteage: "1",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "112",
        product_id: "1120",
        product_name: "Rollers & Curlers",
        product_brand:"Nykaa",
        product_description: "Nykaa VHSCC-01 3 In 1 Hair Styler",
        product_rating: "3.2",
        product_rating_count: "2087",
        product_img: "https://images-static.nykaa.com/media/catalog/product/1/5/15f625a8904086303074_1.jpg",
        product_price: "1999",
        product_discount_price: "1499",
        product_discount_percenteage: "25",
        product_color: "brown",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1121",
        product_name: "Hair  Cream",
        product_brand:"",
        product_description: "Streax Professional Argan Secrets Hair Colourant Cream - Dark Ash Blonde ",
        product_rating: "2.1",
        product_rating_count: "359",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/f/9f124e28901247572317.jpg",
        product_price: "180",
        product_discount_price: "171",
        product_discount_percenteage: "5",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1122",
        product_name: "Hair Color",
        product_brand:"",
        product_description: "L'Oreal Paris Casting Creme Gloss Hair Color - 300 Darkest Brown",
        product_rating: "4.3",
        product_rating_count: "",
        product_img: "https://images-static.nykaa.com/media/catalog/product/1/5/15d16488901526101023_1.jpg",
        product_price: "550",
        product_discount_price: "497",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1123",
        product_name: "Hair Color",
        product_brand:"Nykaa",
        product_description: "Indus Valley Organically Natural Hair Color - Black",
        product_rating: "4.4",
        product_rating_count: "890",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/c/4c93decnyivon0000001-1.jpg",
        product_price: "599",
        product_discount_price: "569",
        product_discount_percenteage: "5",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1124",
        product_name: "Hair Color ",
        product_brand:"Nivea",
        product_description: "Revlon Colorsilk Hair Color - Deep Burgundy 3DB",
        product_rating: "2.8",
        product_rating_count: "232",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/4/b42cf9c8902656700599_1.jpg",
        product_price: "435",
        product_discount_price: "348",
        product_discount_percenteage: "20",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1125",
        product_name: "Straight",
        product_brand:"Olay",
        product_description: "Toni&Guy Heat Protection Mist",
        product_rating: "2.7",
        product_rating_count: "150",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/4/e432a28079400204585_HERO.jpg",
        product_price: "879",
        product_discount_price: "747",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1126",
        product_name: " Hair Color",
        product_brand:"",
        product_description: "Garnier Color Naturals Creme Hair Color",
        product_rating: "3.8",
        product_rating_count: "234",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/7/3/7329d7d8901526539314_0.jpg",
        product_price: "200",
        product_discount_price: "160",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1127",
        product_name: "Aloe Vera Gel",
        product_brand:"Nykaa",
        product_description: "Nykaa Naturals Aloe Vera Gel",
        product_rating: "3.7",
        product_rating_count: "243",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/9/8904245714277_1.jpg",
        product_price: "399",
        product_discount_price: "319",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1128",
        product_name: "Gels & Waxes",
        product_brand:"",
        product_description: "The Man Company Sportivo Hair Styling Pomade",
        product_rating: "1.5",
        product_rating_count: "222",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/a/bab61aa8907367002499_5.jpg",
        product_price: "349",
        product_discount_price: "286",
        product_discount_percenteage: "18",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1129",
        product_name: "Gel",
        product_brand:"Nykaa",
        product_description: "Jeva Aloevera Gel For Young Radiant Skin & Hair",
        product_rating: "3.9",
        product_rating_count: "40",
        product_img: "https://images-static.nykaa.com/media/catalog/product/6/a/6aeb37b7452213788320_1.jpg",
        product_price: "250",
        product_discount_price: "175",
        product_discount_percenteage: "30",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "113",
        product_id: "1130",
        product_name: "Gel & Wax",
        product_brand:"",
        product_description: "Ktein Natural Mix & Boost",
        product_rating: "2.8",
        product_rating_count: "242",
        product_img: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/d/6/d63f00bKTEIN00000014_1.jpg",
        product_price: "400",
        product_discount_price: "360",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: false
    },


    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1131",
        product_name: "Shampoo",
        product_brand:"Maybelline",
        product_description: "True Frog Shampoo For Curls + True Frog Everyday Hair Conditioner + True Frog Deep Conditioning Mask",
        product_rating: "4.6",
        product_rating_count: "459",
        product_img: "https://images-static.nykaa.com/media/catalog/product/t/r/truab00000002.jpg",
        product_price: "2000",
        product_discount_price: "1800",
        product_discount_percenteage: "10",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1132",
        product_name: "Straight",
        product_brand:"",
        product_description: "Alan Truman The Blow Brush Gold Ceramic",
        product_rating: "3.8",
        product_rating_count: "881",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/a/ca221f1712383468796_2.jpg",
        product_price: "3749",
        product_discount_price: "3374",
        product_discount_percenteage: "10",
        product_color: "golden",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1133",
        product_name: "Shampoo",
        product_brand:"Nykaa",
        product_description: "Schwarzkopf Professional Bonacure Keratin Smooth Perfect Micellar Shampoo",
        product_rating: "4.4",
        product_rating_count: "389",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/0/e0cd67e4045787429558new1.jpg",
        product_price: "1000",
        product_discount_price: "950",
        product_discount_percenteage: "5",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1134",
        product_name: "Straight",
        product_brand:"",
        product_description: "Streak Street Wet And Dry Hair Detangler Hair Brush With Spacing Clip - Blue",
        product_rating: "4.7",
        product_rating_count: "18",
        product_img: "https://images-static.nykaa.com/media/catalog/product/6/2/628391a8904368203412.jpg",
        product_price: "500",
        product_discount_price: "299",
        product_discount_percenteage: "20",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1135",
        product_name: "Straight",
        product_brand:"",
        product_description: "Scalppie Hair Scalp Massager & Shampoo Brush - Butterball Yellow - Promotes Hair Growth & Prevents Dandruff",
        product_rating: "2.6",
        product_rating_count: "58",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/a/9abf3c28904368201838_1.jpg",
        product_price: "600",
        product_discount_price: "299",
        product_discount_percenteage: "50",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1136",
        product_name: "Straight",
        product_brand:"Nykaa",
        product_description: "Nykaa Scalp Massager Brush For Blood Circulation & Natural Hair Growth - Pink",
        product_rating: "1.5",
        product_rating_count: "300",
        product_img: "https://images-static.nykaa.com/media/catalog/product/d/7/d7b03d2NYKAB00000247_1.jpg",
        product_price: "499",
        product_discount_price: "424",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1137",
        product_name: "Hair Serum ",
        product_brand:"Maybelline",
        product_description: "Streax Hair Serum with Walnut Oil",
        product_rating: "1.8",
        product_rating_count: "240",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/b/8b6164d8901247573994(1).jpg",
        product_price: "108",
        product_discount_price: "105",
        product_discount_percenteage: "3",
        product_color: "golden",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1138",
        product_name: "Shampoo",
        product_brand:"Blue Heaven",
        product_description: "Anomaly Gentle Shampoo for All Hair Types with Rosemary & Grapefruit",
        product_rating: "3.1",
        product_rating_count: "98",
        product_img: "https://images-static.nykaa.com/media/catalog/product/5/c/5c143daANOAA00000001_1.jpg",
        product_price: "800",
        product_discount_price: "760",
        product_discount_percenteage: "5",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1139",
        product_name: "Shampoo",
        product_brand:"Maybelline",
        product_description: "Brillare Hair Fall Control Shampoo + Intenso",
        product_rating: "2.5",
        product_rating_count: "235",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/f/0fff65dBRILL00000041-1.jpg",
        product_price: "890",
        product_discount_price: "846",
        product_discount_percenteage: "5",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "114",
        product_id: "1140",
        product_name: "Shampoo & Conditioner",
        product_brand:"Nykaa",
        product_description: "Nykaa Naturals Onion & Fenugreek Shampoo & Conditioner - Hair Growth Combo",
        product_rating: "2.3",
        product_rating_count: "956",
        product_img: "https://images-static.nykaa.com/media/catalog/product/a/9/a9f4173NYNYKBC001421w_1.jpg",
        product_price: "798",
        product_discount_price: "678",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },


    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1141",
        product_name: "Hairfall & Thinning",
        product_brand:"",
        product_description: "Power Gummies - Hair & Nails Vitamins With Biotin",
        product_rating: "2.2",
        product_rating_count: "2321",
        product_img: "https://images-static.nykaa.com/media/catalog/product/b/2/b2987f68908010907000-1.jpg",
        product_price: "1200",
        product_discount_price: "1080",
        product_discount_percenteage: "15",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1142",
        product_name: "Shampoo",
        product_brand:"Olay",
        product_description: "Matrix Opti Care Smooth Straight Professional Shampoo with Shea Butter-For Ultra Smooth Hair-Paraben Free",
        product_rating: "4.3",
        product_rating_count: "423",
        product_img: "https://images-static.nykaa.com/media/catalog/product/7/2/7266e6eNYMATRIX00108_aa1.jpg",
        product_price: "400",
        product_discount_price: "360",
        product_discount_percenteage: "10",
        product_color: "golden",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1143",
        product_name: "Shampoo & Conditioner",
        product_brand:"Nykaa",
        product_description: "Nykaa Naturals Apple Cider Vinegar & Ginger Shampoo & Conditioner- Anti-Dandruff Combo",
        product_rating: "4.1",
        product_rating_count: "890",
        product_img: "https://images-static.nykaa.com/media/catalog/product/c/a/cab5173NYNYKBC001423w_1.jpg",
        product_price: "798",
        product_discount_price: "559",
        product_discount_percenteage: "30",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1144",
        product_name: "Hair  Oil",
        product_brand:"Maybelline",
        product_description: "Brillare Dandruff Control Booster Oil Shots",
        product_rating: "4",
        product_rating_count: "345",
        product_img: "https://images-static.nykaa.com/media/catalog/product/e/7/e7661ac8906034881962_1.jpg",
        product_price: "795",
        product_discount_price: "636",
        product_discount_percenteage: "20",
        product_color: "brown",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1145",
        product_name: "Rollers & Curlers",
        product_brand:"Nykaa",
        product_description: "Dyson Airwrap Complete Hair Styler - Red",
        product_rating: "4.3",
        product_rating_count: "119",
        product_img: "https://images-static.nykaa.com/media/catalog/product/a/8/a85cd725025155048801_0.jpg",
        product_price: "45000",
        product_discount_price: "44550",
        product_discount_percenteage: "1",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1146",
        product_name: "Shampoo",
        product_brand:"",
        product_description: "Wella Professionals INVIGO Nutri Enrich Deep Nourishing Shampoo",
        product_rating: "4.1",
        product_rating_count: "3980",
        product_img: "https://images-static.nykaa.com/media/catalog/product/8/0/8005610639161_8_1.jpg",
        product_price: "700",
        product_discount_price: "630",
        product_discount_percenteage: "10",
        product_color: "golden",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1147",
        product_name: "Anti-Hairfall",
        product_brand:"",
        product_description: "Garnier Fructis Papaya Hair Food - Reparing Papaya Hair Mask For Damaged Hair",
        product_rating: "4.4",
        product_rating_count: "754",
        product_img: "https://images-static.nykaa.com/media/catalog/product/0/e/0ede7d33600542143608_1.jpg",
        product_price: "725",
        product_discount_price: "625",
        product_discount_percenteage: "14",
        product_color: "",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1148",
        product_name: "Shampoo",
        product_brand:"Nivea",
        product_description: "Schwarzkopf Professional Bonacure Peptide Repair Rescue Micellar Shampoo",
        product_rating: "2.5",
        product_rating_count: "3372",
        product_img: "https://images-static.nykaa.com/media/catalog/product/4/d/4d6267e4045787427523new1.jpg",
        product_price: "1200",
        product_discount_price: "960",
        product_discount_percenteage: "20",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1149",
        product_name: "Hair Color",
        product_brand:"Blue Heaven",
        product_description: "Streax Professional Argan Secrets Hair Colourant Cream - Dark Ash Blonde 6.1",
        product_rating: "1.8",
        product_rating_count: "1422",
        product_img: "https://images-static.nykaa.com/media/catalog/product/9/f/9f124e28901247572317.jpg",
        product_price: "180",
        product_discount_price: "162",
        product_discount_percenteage: "10",
        product_color: "Red",
        trending_product: false
    },
    {
        cat_id: "3",
        sub_cat_id: "115",
        product_id: "1150",
        product_name: "Shampoo",
        product_brand:"",
        product_description: "Head & Shoulders Smooth & Silky Anti Dandruff Shampoo",
        product_rating: "2.9",
        product_rating_count: "2311",
        product_img: "https://images-static.nykaa.com/media/catalog/product/a/2/a2715ce4902430908047.jpg",
        product_price: "699",
        product_discount_price: "349",
        product_discount_percenteage: "50",
        product_color: "",
        trending_product: false
    },
]